version: '3.9'

services:
  db:
    container_name: postgres-graphql
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs-graphql
    networks:
      - env_net
  api:
    container_name: api-graphql
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nestjs-graphql?schema=public
      - PORT=3002
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - db
    networks:
      - env_net
    command: sh -c "npx prisma db push && npm start && tail -f /dev/null"

networks:
  env_net:
    driver: bridge
